apiVersion: apps/v1
kind: Deployment
metadata:
  name: framework-educativo-user
  labels:
    app: framework-educativo-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: framework-educativo-user
  template:
    metadata:
      labels:
        app: framework-educativo-user
    spec:
      containers:
        - name: framework-educativo-user
          image: tronxi/framework-educativo-user:${USER_TAG}
          resources:
            limits:
              cpu: "0.9"
              memory: "900Mi"
            requests:
              cpu: "0.8"
              memory: "800Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 30
          env:
            - name: profile
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: profile
            - name: clave
              valueFrom:
                secretKeyRef:
                  name: framework-educativo-secret
                  key: clave
            - name: rabbit_pass
              valueFrom:
                secretKeyRef:
                  name: framework-educativo-secret
                  key: rabbit_pass
            - name: eureka_host
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: eureka_host
            - name: rabbit_host
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: rabbit_host
            - name: user_service
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: user_service
            - name: user_db
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: user_db
            - name: secret_token
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: secret_token

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: framework-educativo-user
spec:
  selector:
    app: framework-educativo-user
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: framework-educativo-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: framework-educativo-user
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50