spring:
  datasource:
    url: jdbc:h2:mem:h2prueba
    driverClassName: org.h2.Driver
  h2:
    console:
        path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
environment: local
eureka:
  instance:
    status-page-url-path: /swagger-ui.html
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5