spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
  datasource:
    username: pi
    password: ENC(+Tb6CL+hH5md5GjPcqoz2PRUrl2KopUp)
    url: jdbc:mysql://${user-db}:3306/framework-educativo-user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    #initialization-mode: embedded
  application:
    name: user
server:
  port: 8081

user-service: user-service
user-db: 192.168.1.7

secret-token: "default-secret-token"

eureka:
  instance:
    status-page-url-path: /actuator/health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: ${user-service}
  client:
    serviceUrl:
      defaultZone: ${eureka-host}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5