spring:
  datasource:
    username: pi
    password: servidortfg
  application:
    name: "user"
  cloud:
    client:
      hostname: http://raspberrytronxi.ddns.net
server:
  port: 8081
comun: application
environment: defecto