spring:
  datasource:
    username: pi
    password: ENC(+Tb6CL+hH5md5GjPcqoz2PRUrl2KopUp)
  application:
    name: user
#  cloud:
#    client:
#      hostname: http://raspberrytronxi.ddns.net
server:
  port: 8081

comun: application
environment: defecto