spring:
  datasource:
    username: pi
    password: servidortfg
  application:
    name: user
  cloud:
    client:
      hostname: http://raspberrytronxi.ddns.net
server:
  port: 8081
  ssl:
    key-store-type: PKCS12
    key-store: classpath:framework-certificate.p12
    key-store-password: changeme
    key-alias: framework-educativo
comun: application
environment: defecto