spring:
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/framework-educativo-dev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: embedded
environment: dev
eureka:
  instance:
    status-page-url-path: /swagger-ui.html
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://192.168.1.9:8762/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5