#spring:
#  datasource:
#    url: jdbc:h2:mem:h2prueba
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#        path: /h2-console
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
spring:
  datasource:
    url: jdbc:mysql://raspberrytronxi.ddns.net:3306/framework-educativo-user-dev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: embedded
environment: local
eureka:
  instance:
    status-page-url-path: http://localhost:${server.port}/actuator/health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5