spring:
  datasource:
    url: jdbc:mysql://104.199.45.227:3306/framework-educativo-user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: embedded
environment: dev
eureka-host: raspberrytronxi2.ddns.net
eureka:
  instance:
    status-page-url-path: ${spring.cloud.client.hostname}:${server.port}/actuator/health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${eureka-host}:8762/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
