spring:
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/framework-educativo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
environment: pro